[package]
name = "bedpool"
version = "0.1.0"
authors = ["wsowens <wowens@ufl.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"